sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - 'node'
  - 'lts/*'
  - '8'
  - '7'
  - '6'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
script:
  - npm run test:single
  - npm run check-coverage
  - npm run lint
  - npm run build
after_success:
  - npm run report-coverage
  - npm run semantic-release
