sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '5'
  - '4'
  - '4.4'
  - '4.3'
  - '4.2'
  - '4.1'
  - '4.0'
  - '0.12'
  - '0.11'
  - '0.10'
  - '0.8'
  - '0.6'
  - 'iojs'
  - 'node'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
script:
  - npm run test:single
  - npm run check-coverage
  - npm run lint
  - npm run build
after_success:
  - npm run report-coverage
  - npm run semantic-release
